on: [workflow_call]

name: Warm-up caches

jobs:
  toolchain:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy, llvm-tools

      - name: Configure cache
        id: cache
        uses: ./.github/actions/cache
        with:
          rustc: ${{ steps.toolchain.outputs.rustc_hash }}
          toolchain: read-write

      - name: Install coverage tool
        if: steps.cache.outputs.toolchain != 'true'
        shell: bash
        run: which grcov || cargo install grcov

      - name: Install cross compiler
        if: steps.cache.outputs.toolchain != 'true'
        shell: bash
        run: which cross || cargo install cross

  project:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy, llvm-tools

      - name: Configure cache
        id: cache
        uses: ./.github/actions/cache
        with:
          rustc: ${{ steps.toolchain.outputs.rustc_hash }}
          toolchain: read
          compiled: read

      - name: Compile project
        if: steps.cache.outputs.compiled != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Save cache
        if: steps.cache.outputs.compiled != 'true'
        uses: ./.github/actions/cache
        with:
          rustc: ${{ steps.toolchain.outputs.rustc_hash }}
          compiled: write
